FROM node:17.6.0-alpine3.15 AS vue-build

RUN apk update && apk upgrade

COPY ./public/koordinattransformation-vue/ /koordinattransformation/

RUN npm install -g @vue/cli \
  @vue/cli-service \
  @vue/cli-plugin-babel \
  @vue/cli-plugin-eslint \
  @vue/cli-plugin-pwa \
  @vue/cli-plugin-router \
  @vue/cli-plugin-vuex \
  @vue/compiler-sfc \
  vue-cli-plugin-style-resources-loader
WORKDIR /koordinattransformation
RUN npm install --legacy-peer-deps
#RUN npm install && npm audit fix --production
RUN npm run build-test




FROM nginx:1.21.6-alpine

RUN apk update && apk upgrade

RUN apk add openssl libaio

RUN adduser nginx root

COPY --from=vue-build /koordinattransformation/dist /usr/share/nginx/html
COPY nginx.test.conf /etc/nginx/nginx.conf
COPY ./SecHeaders.conf /etc/nginx/SecHeaders.conf

RUN apk add tzdata
RUN export TZ="Europe/Copenhagen"
RUN cp /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
RUN echo "Europe/Copenhagen" > /etc/timezone
RUN apk del tzdata
